"""selection:dropped

Revision ID: 50af700b344d
Revises: None
Create Date: 2014-03-09 12:45:04.793304

"""

# revision identifiers, used by Alembic.
revision = '50af700b344d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selection')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selection',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('page_id', sa.INTEGER(), nullable=True),
    sa.Column('sentence_id', sa.INTEGER(), nullable=True),
    sa.Column('translation_id', sa.INTEGER(), nullable=True),
    sa.Column('ctime', sa.DATETIME(), nullable=False),
    sa.Column('mtime', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], [u'page.id'], ),
    sa.ForeignKeyConstraint(['sentence_id'], [u'sentence.id'], ),
    sa.ForeignKeyConstraint(['translation_id'], [u'translation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
