"""selection:recreated_with_page_id_removed

Revision ID: 6b2aea0c428
Revises: 50af700b344d
Create Date: 2014-03-09 13:21:11.890962

"""

# revision identifiers, used by Alembic.
revision = '6b2aea0c428'
down_revision = '50af700b344d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.Column('translation_id', sa.Integer(), nullable=True),
    sa.Column('ctime', sa.DateTime(), nullable=False),
    sa.Column('mtime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], [u'sentence.id'], ),
    sa.ForeignKeyConstraint(['translation_id'], [u'translation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selection')
    ### end Alembic commands ###
